import type React from 'react'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from '@/app/_components/wrappers/theme-provider'
import { Navbar } from '@/app/_components/navbar/Navbar'
import { UserPrefsSettings } from '@/app/_components/wrappers/prefs'
import '@/styles/globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body>
                <ThemeProvider
                    defaultTheme="system"
                    defaultColorTheme="default"
                >
                    <div className="relative min-h-screen">
                        <Navbar />
                        <main className="flex-1">{children}</main>
                        <div className="fixed right-10 bottom-10">
                            <UserPrefsSettings />
                        </div>
                        <footer></footer>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
