import type React from "react"
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { ThemeProvider } from "@/components/navbar/theme-provider"
import { Navbar } from "@/components/navbar/Navbar"
import '@/styles/globals.css'


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider defaultTheme="system" defaultColorTheme="default">
          <div className="flex min-h-screen flex-col">
            <Navbar />
            <main className="flex-1">
              {children}
              </main>
            <footer></footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
